#
# Java makefile.
#
# Copyright (c) 1996 Intelligent Switched Systems, Sydney
# $Id$
#

#JAVAOPTIONS := 
#JAVACOPTIONS :=
TESTS := PropertyTreeTest.java TestHarness.java DictionaryConverterTest.java
ROOTNAME := com
SUBDIRS := Test
INSTALLPATH := etc
INSTALLFILES := InetGateway.prp
EXCLUDECLASSES := TestHarness.class PropertyTreeTest.class DictionaryConverterTest.class DictionaryConverterTest$$TestClass1.class DictionaryConverterTest$$TestClass2.class TestHarness$$1.class

include $(JETTY_HOME)/etc/Global.mk

