#
# Java makefile.
#
# Copyright (c) 1996 Intelligent Switched Systems, Sydney
# $Id$
#

#JAVAOPTIONS := 
#JAVACOPTIONS :=
TESTS := TestHarness.java
ROOTNAME := com
SUBDIRS := STF Gateway
INSTALLPATH := etc
INSTALLFILES := InetGateway.prp

include $(JETTY_HOME)/etc/Global.mk
tests:
	make -C Test all
