#
# Java makefile.
#
# Copyright (c) 1996 Intelligent Switched Systems, Sydney
# $Id$
#

#JAVAOPTIONS := 
#JAVACOPTIONS :=
TESTS := 
ROOTNAME := uk
EXCLUDECLASSES :=           

INSTALLPATH := .
INSTALLFILES := 

all: 

include $(JETTY_HOME)/etc/Global.mk
