#
# Java makefile.
#
#Copyright (C) 2000 by Mortbay Consulting Ltd
# $Id$
#

TESTS := ObjectConverterTest.java
ROOTNAME := com
EXCLUDECLASSES := ObjectConverterTest.class ObjectConverterTest$$TestClass1.class ObjectConverterTest$$TestClass2.class ObjectConverterTest$$A.class ObjectConverterTest$$B.class

include $(JETTY_HOME)/etc/Global.mk

