#
# Java makefile.
#
# Copyright (c) 1996 Intelligent Switched Systems, Sydney
# $Id$
#

#JAVAOPTIONS := 
#JAVACOPTIONS :=
TESTS :=
ROOTNAME := com

# The contrib dirs like to see the main Jetty code base...
CLASSPATH := ${CLASSPATH}:$(JETTY_HOME)/src

include $(JETTY_HOME)/etc/Global.mk

