#
# Java makefile.
#
# Copyright (c) 1996 Intelligent Switched Systems, Sydney
# $Id$
#

#JAVAOPTIONS := 
#JAVACOPTIONS :=
TESTS := TestHarness.java 
ROOTNAME := com
BINFILES := 
CFGFILES := 

include $(JETTY_HOME)/etc/Global.mk
