#
# Java makefile.
#
# Copyright (c) 1996 Intelligent Switched Systems, Sydney
# $Id$
#

#JAVAOPTIONS := 
#JAVACOPTIONS :=
TESTS := TestHarness.java
ROOTNAME := com
SUBDIRS := DataClassTest
INSTALLPATH := etc
INSTALLFILES := InetGateway.prp
EXCLUDECLASSES := \
	TestHarness.class \
	PropertyTreeTest.class \
	DictionaryConverterTest.class \
	DictionaryConverterTest$$TestClass1.class \
	DictionaryConverterTest$$TestClass2.class \
	TestHarness$$1.class \
	TestHarness$$2.class \
	TestHarness$$TestThreadedServer.class \
	TestHarness$$TestThreadPool.class \

include $(JETTY_HOME)/etc/Global.mk

