#
# Java makefile.
#
# Copyright (c) 1996 Intelligent Switched Systems, Sydney
# $Id$
#

#JAVAOPTIONS := 
#JAVACOPTIONS :=
TESTS :=
ROOTNAME := javax
SUBDIRS := tagext

CLASSFILES += $(wildcard *.properties *.class)

include $(JETTY_HOME)/etc/Global.mk
