#
# Java makefile.
#
# Copyright (c) 1996 Intelligent Switched Systems, Sydney
# $Id$
#


#JAVAOPTIONS := 
#JAVACOPTIONS :=
TESTS := 
EXCLUDECLASSES := 
ROOTNAME := com
BINFILES := 
CFGFILES := 
SUBDIRS := 
EXCLUDE := 

include $(JETTY_HOME)/etc/Global.mk


