#
# Java makefile.
#
# Copyright (c) 1996 Intelligent Switched Systems, Sydney
# $Id$
#

#JAVAOPTIONS := 
#JAVACOPTIONS :=
TESTS := 
ROOTNAME := com
EXCLUDECLASSES :=           


INSTALLPATH := .
INSTALLFILES := 

all: 

NATIVE := SetUID.java
NATIVE := SetUID.java
NATIVELIB := SetUID

include $(JETTY_HOME)/etc/Global.mk
