#
# Java makefile.
#
# Copyright (c) 1996 Intelligent Switched Systems, Sydney
# $Id$
#

rall:

#JAVAOPTIONS := 
#JAVACOPTIONS :=
TESTS :=
ROOTNAME := src

SUBDIRS := javax/servlet com org/apache/jasper

include $(JETTY_HOME)/etc/Global.mk
