#
# Java makefile.
#
# Copyright (c) 1996 Intelligent Switched Systems, Sydney
# $Id$
#

#JAVAOPTIONS := 
#JAVACOPTIONS :=
TESTS :=
ROOTNAME := com
EXCLUDECLASSES := T1.class T2.class

include $(JETTY_HOME)/etc/Global.mk
