#
# Java makefile.
#
# Copyright (c) 1997 Intelligent Switched Systems, Sydney
# $Id$
#

#JAVAOPTIONS := 
#JAVACOPTIONS :=
ROOTNAME := com
TESTS := Log.java Code.java Test.java Frame.java

ifndef MORTBAY_HOME
MORTBAY_HOME := /usr/local/MortBay
endif
include $(MORTBAY_HOME)/etc/Global.mk
