#
# Java makefile.
#
# Copyright (c) 1997 Intelligent Switched Systems, Sydney
# $Id$
#

#JAVAOPTIONS := 
#JAVACOPTIONS :=
ROOTNAME := com
TESTS := TestHarness.java
EXCLUDECLASSES := TestHarness.class

include $(JETTY_HOME)/etc/Global.mk
