#
# Java makefile.
#
# Copyright (c) 1997 Intelligent Switched Systems, Sydney
# $Id$
#

#JAVAOPTIONS := 
#JAVACOPTIONS :=
ROOTNAME := com
TESTS := Log.java Code.java Test.java Frame.java

include $(JETTY_HOME)/etc/Global.mk
