#
# Java makefile.
#
# Copyright (c) 1996 Intelligent Switched Systems, Sydney
# $Id$
#

#JAVAOPTIONS := 
#JAVACOPTIONS :=
TESTS := TestHtml.java
ROOTNAME := com
EXCLUDECLASSES := TestHtml.class

include $(JETTY_HOME)/etc/Global.mk
