#
# Java makefile.
#
# Copyright (c) 1996 Intelligent Switched Systems, Sydney
# $Id$
#

#JAVAOPTIONS := 
#JAVACOPTIONS :=
TESTS :=
ROOTNAME := com

include $(JETTY_HOME)/etc/Global.mk

install:
	mkdir -p $(INSTALLROOT)/servlets/com/mortbay/Servlet
	cp Dump.class $(INSTALLROOT)/servlets/com/mortbay/Servlet
