#
# Java makefile.
#
# Copyright (c) 1996 Intelligent Switched Systems, Sydney
# $Id$
#

#JAVAOPTIONS := 
#JAVACOPTIONS :=
ROOTNAME := com
BINFILES := 
CFGFILES := 

TESTS := TestFtp.java

all: 

include $(JETTY_HOME)/etc/Global.mk
