#
# Java makefile.
#
# Copyright (c) 1996 Intelligent Switched Systems, Sydney
# $Id$
#

#JAVAOPTIONS := 
#JAVACOPTIONS :=
TESTS :=
ROOTNAME := org
EXCLUDECLASSES :=  $(wildcard *.class )
CLASSPATH := ../../../../../src

include $(JETTY_HOME)/etc/Global.mk
