#
# Java makefile.
#
# Copyright (c) 1996 Intelligent Switched Systems, Sydney
# $Id$
#

all:

rall: all

#JAVAOPTIONS := 
#JAVACOPTIONS :=
TESTS := Cookies.java HttpTests.java
ROOTNAME := com
BINFILES := 
CFGFILES := 
SUBDIRS = Configure Handler Filter HTML

ifndef MORTBAY_HOME
MORTBAY_HOME := /usr/local/MortBay
endif
include $(MORTBAY_HOME)/etc/Global.mk


