#
# Java makefile.
#
# Copyright (c) 1996 Intelligent Switched Systems, Sydney
# $Id$
#

all:

rall: all

#JAVAOPTIONS := 
#JAVACOPTIONS :=
TESTS := TestHarness.java
EXCLUDECLASSES := \
	TestHarness.class \
	TestRFC2616.class \
	TestRFC2616$$TestConnection.class \

ROOTNAME := com
BINFILES := 
CFGFILES := 
SUBDIRS = 


include $(JETTY_HOME)/etc/Global.mk

