#
# Java makefile.
#
# Copyright (c) 1996 Intelligent Switched Systems, Sydney
# $Id$
#

all:

rall: all

#JAVAOPTIONS := 
#JAVACOPTIONS :=
TESTS := 
EXCLUDECLASSES := TestTEHandler.class 
ROOTNAME := com
BINFILES := 
CFGFILES := 
SUBDIRS = 

include $(JETTY_HOME)/etc/Global.mk

