#
# Java makefile.
#
# Copyright (c) 1996 Intelligent Switched Systems, Sydney
# $Id$
#

#JAVAOPTIONS := 
#JAVACOPTIONS :=
TESTS :=
ROOTNAME := org
SUBDIRS := 

CLASSFILES += $(wildcard *.properties *.dtd)

include $(JETTY_HOME)/etc/Global.mk
