#
# Java makefile.
#
# Copyright (c) 1996 Intelligent Switched Systems, Sydney
# $Id$
#

rall:

#JAVAOPTIONS := 
#JAVACOPTIONS :=
TESTS :=
ROOTNAME := com
SUBDIRS := Base Util FTP JDBC  HTML  HTTP Servlets Jetty 


include $(JETTY_HOME)/etc/Global.mk
