#
# Java makefile.
#
# Copyright (c) 1996 Intelligent Switched Systems, Sydney
# $Id$
#

rall:

#JAVAOPTIONS := 
#JAVACOPTIONS :=
TESTS :=
ROOTNAME := src

SUBDIRS := javax com

ifndef MORTBAY_HOME
MORTBAY_HOME := ${PWD}/..
endif
include $(MORTBAY_HOME)/etc/Global.mk

